#!/bin/bash

case "$1" in
  install)
    npm install > /dev/null 2>&1
    exit $?
    ;;
  
  test)
    npm install > /dev/null 2>&1
    
    npm run build > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Build failed."
      exit 1
    fi

    mkdir -p coverage

    touch coverage/output.txt
    touch coverage/dump.txt
    
    npm run test 
    if [ $? -ne 0 ]; then
      echo "Tests failed."
      exit 1
    fi
    exit $?
    ;;

  start)
    npm install > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Dependency installation failed."
      exit 1
    fi
    npm run build > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Build failed."
      exit 1
    fi
    node dist/index.js
    exit $?
    ;;
  
  *)
    npm install > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Dependency installation failed."
      exit 1
    fi
    npm run build > /dev/null 2>&1
    if [ $? -ne 0 ]; then
      echo "Build failed."
      exit 1
    fi
    # Pass all arguments to the node command
    node dist/index.js "$@"
    exit $?
    ;;
esac